### ISSUE TITLE
Config file used for training

### ISSUE THREAD

**Issue by eypros** [ahmetozlu/tensorflow_object_counting_api#10]
I am interested in training an SSD model myself and I was wondering if you could provide the config file you used to train your model. 
Your model seem to work quite well for detecting objects.

I have downloaded the samples from model in tensorflow object detection but somehow I feel I am missing something.

**Comment by ahmetozlu** [comment]
I have not trained SSD MobilNet by my own, I just used trained SSD MobilNet weights from [TensorFlow Models Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).
