### ISSUE TITLE
Code Implementation

### ISSUE THREAD

**Issue by SalsHacker** [ahmetozlu/tensorflow_object_counting_api#13]
I am getting the error-
`Traceback (most recent call last):
  File "carxcount.py", line 22, in <module>
    detection_graph, category_index = backbone.set_model('ssd_mobilenet_v1_coco_2017_11_17')
NameError: name 'backbone' is not defined`

**Comment by ahmetozlu** [comment]
Can you try to run the program on python3?

**Comment by bidyutchanda** [comment]
Did you clone the whole repo or did you download just one file?
