### ISSUE TITLE
Question about cumulative_object_counting_x_axis

### ISSUE THREAD

**Issue by cAstraea** [ahmetozlu/tensorflow_object_counting_api#15]
Hello, having a bit of problem with pedestrian detection. tried the pedestrian detection demo with my video ( a narrow hallway ). Modified the ROI line also but i can't get it to pick up the person. Tried different model frozen .pb also without success.   
The cumulative_object_counting_y_axis seems to work a little bit better for my case but I would like to put the ROI line on vertical or at least slanted at an angle to detect people passing through a doorway into and out of the hallway. 

Here's an example . How would I go about moving the ROI on the door to the right ? 
![image](https://user-images.githubusercontent.com/13070662/48399023-267aeb80-e72b-11e8-99ee-61ed420c795f.png)

**Comment by ahmetozlu** [comment]
You should set the [roi_position](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/pedestrian_counting.py#L20) variable to set ROI Line position!
