### ISSUE TITLE
Variable that counts the cars

### ISSUE THREAD

**Issue by rafabaroni** [ahmetozlu/tensorflow_object_counting_api#16]
Hi, I would like to know what's the variable that counts the cars detected in the video and in which file is located.

![sem titulo](https://user-images.githubusercontent.com/45096948/48620285-7cec6200-e997-11e8-81d5-28b39f4f7b72.png)

**Comment by ahmetozlu** [comment]
The variable name is "**counting_result**", it can be found in [this line](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/api/object_counting_api.py#L478).
