### ISSUE TITLE
How to try new dataset based on my data

### ISSUE THREAD

**Issue by varmatangoit** [ahmetozlu/tensorflow_object_counting_api#18]
Hi
  Using this algorithm I can able detected vehicle and color of the vehicle, but I need more information like make and model of the vehicle for that I need to train based on my dataset. Can you help me how to train dataset on this algorithm?

**Comment by ahmetozlu** [comment]
You need to perform "Transfer Learning" on one of the trained models. You can find tons of tutorials about it and **[here](https://www.quora.com/How-can-I-do-transfer-learning-with-TensorFlow-I-have-weights-of-all-the-layers-of-InceptionV3-as-numpy-array-which-I-got-from-the-ckpt-file-of-an-inception-model)** is a resource that can help you about it.

**Comment by ahmetozlu** [comment]
[**Custom training**](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/custom_object_training) module has been developed currently and it will be published soon. Thus, you can perform transfer learning on trained model to develop your custom object counting systems.

**Comment by git-ankur-shukla** [comment]
@ahmetozlu any ideas how can i contribute to this custom training module. I would love to contribute.

**Comment by ahmetozlu** [comment]
Hi @git-ankur-shukla,

First of all, thanks a lot for your interest and willingness to contribute! I think it would be great to develop a sample project which provides a custom trained model for detection, tracking and counting the custom objects using TensorFlow Object Counting API. The sample project might contains these stuff:

- custom dataset (such as vehicle dataset contains vehicle model name label (such as Toyota Corolla, Mercedes E250 etc.))
- the frozen inference graph
- source codes and utils which are used to train model
- a clear and well designed readme documentation to explain all the details
- output video for demonstration (the readers of this project should see that the model can detect/track and count the vehicles as well as detect the models and predict the speed nad color of these vehicles)

I would want to develop this sample project but it is difficult to find time to work on it for me! If I can get your support it would be great to make this Counting API more powerful and useful. Moreover, the readers of your project will see that how can they train their own custom model to count any custom objects. It sounds awesome!

I hope, this makes sense for you! What do you think about it! I am looking forward to hear your feedback and also your contributions!

Sincerely,
Ahmet

**Comment by ahmetozlu** [comment]
https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/20#issuecomment-447818120
