### ISSUE TITLE
How to use targeted_objects = "cow" in cumulative_object_counting_x_axis

### ISSUE THREAD

**Issue by MaTaDoRcpe** [ahmetozlu/tensorflow_object_counting_api#20]

**Comment by ahmetozlu** [comment]
**[Custom training module](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/custom_object_training)** has been developed currently and it will be published soon. Thus, you can perform transfer learning on trained model to develop your custom object counting systems.
