### ISSUE TITLE
How to count the number of any class which is not present in COCO dataset?

### ISSUE THREAD

**Issue by sahatprasad** [ahmetozlu/tensorflow_object_counting_api#21]
I have been building a toy(which is not present in COCO) detection dataset based in tensorflow object detection API. I have followed this github repository for my project [model](https://towardsdatascience.com/building-a-toy-detector-with-tensorflow-object-detection-api-63c0fdf2ac95),[Github](https://github.com/priya-dwivedi/Deep-Learning/tree/master/tensorflow_toy_detector).

But now I also want to count the number of toys present and saw your repository.
Can you please tell what should I change in this Github repository and the information which I can use from my previous work.

**Comment by ahmetozlu** [comment]
**[Custom training module](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/custom_object_training)** has been developed currently and it will be published soon. Thus, you can perform transfer learning on trained model to develop your custom object counting systems.

**Comment by dmrhmt** [comment]
I have the same problem, I could'nt figure it out where to put my trained data. 
Are there any development on custom training module?

**Comment by ahmetozlu** [comment]
A sample project added to guide you about training your own object detector with your own data to develop your own custom object counting system! Please, check **[this sample project](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/smurf_counter_training)**!
