### ISSUE TITLE
Tensorflow object counting with using C#.Net

### ISSUE THREAD

**Issue by prakashkborntowin** [ahmetozlu/tensorflow_object_counting_api#23]
i'm looking below requirements with C#.net
Recognition of approximate vehicle color
Detection of vehicle direction of travel
Prediction the speed of the vehicle
Prediction of approximate vehicle size
Detection of vehicle Category

**Comment by ahmetozlu** [comment]
Currently, I am not planning to develop vehicle counting project on C# and this is not an issue for the vehicle counting project that has been developed on python.
