### ISSUE TITLE
Threshold and false positives 

### ISSUE THREAD

**Issue by cAstraea** [ahmetozlu/tensorflow_object_counting_api#24]
Hello, how can I adjust a threshold ? I remember before was playing with other examples and they used something like classes[i] == 1 -> this is person 
and scores[i] > my threshold but can't find anything like this in this code.
This were obtained from  (boxes, scores, classes, num) = self.sess.run(some stuff)

**Comment by ahmetozlu** [comment]
You can set the threshold value in [visualization_utils.py](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/utils/visualization_utils.py) by using [min_score_value](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/utils/visualization_utils.py#L618) variable!
