### ISSUE TITLE
How to get counting value of all the entered cars?

### ISSUE THREAD

**Issue by shivakutty** [ahmetozlu/tensorflow_object_counting_api#3]
in the below example images, second car is not detected? Why?

![1](https://user-images.githubusercontent.com/15682985/44001153-09705e82-9e4a-11e8-839b-f65758f33b56.png)
![2](https://user-images.githubusercontent.com/15682985/44001154-09a89022-9e4a-11e8-884a-ce967cd05035.png)
![counter3](https://user-images.githubusercontent.com/15682985/44001158-144e9ae4-9e4a-11e8-8644-8181a39bc07d.png)

**Comment by ahmetozlu** [comment]
It is detected, what do you mean? Could you specify your observation?

**Comment by taojin1992** [comment]
I guess the meaning is:
From the 1st image, the first vehicle detected is a silver car; in the 2nd image, there is a black vehicle and it comes after that silver car (the count is still 1 though, which should be 2); in the 3rd image, a new black car following the black car in 2nd image appears. The count should be 3 here.

**Comment by ahmetozlu** [comment]
fixed
