### ISSUE TITLE
NameError: name 'urllib' is not defined

### ISSUE THREAD

**Issue by Haortiz10** [ahmetozlu/tensorflow_object_counting_api#30]
Hi, i'm getting this error 
I hope you could help me, thanks in advance

~\AppData\Local\Continuum\anaconda3\lib\site-packages\utils\backbone.py in set_model(model_name)
     25         # Download Model if it has not been downloaded yet
     26         if (model_found == 0):
---> 27                 opener = urllib.request.URLopener()
     28                 opener.retrieve(download_base + model_file, model_file)
     29                 tar_file = tarfile.open(model_file)

NameError: name 'urllib' is not defined

**Comment by ahmetozlu** [comment]
Please check **[this](https://stackoverflow.com/questions/42314025/nameerror-name-urllib-is-not-defined)** out!
