### ISSUE TITLE
visualization_utils error

### ISSUE THREAD

**Issue by geoJaSON** [ahmetozlu/tensorflow_object_counting_api#31]
Hi, I'm getting this error when trying to load the API. I've installed the modified utils files and I've verified that visualization_utils.py in the utils folder has the correct function. Thanks!

AttributeError                            Traceback (most recent call last)
<ipython-input-13-411d7442676c> in <module>
     17 deviation = 1 # the constant that represents the object counting area
     18 
---> 19 object_counting_api.cumulative_object_counting_x_axis(input_video, detection_graph, category_index, is_color_recognition_enabled, fps, width, height, roi, deviation) # counting all the objects

~\AppData\Local\Programs\Python\Python37\Lib\site-packages\tensorflow\models\research\object_detection\api\object_counting_api.py in cumulative_object_counting_x_axis(input_video, detection_graph, category_index, is_color_recognition_enabled, fps, width, height, roi, deviation)
     72 
     73                 # Visualization of the results of a detection.
---> 74                 counter, csv_line, counting_mode = vis_util.visualize_boxes_and_labels_on_image_array_x_axis(cap.get(1),
     75                                                                                                              input_frame,
     76                                                                                                              1,
AttributeError: module 'utils.visualization_utils' has no attribute 'visualize_boxes_and_labels_on_image_array_x_axis'

**Comment by ahmetozlu** [comment]
There are not any errors in visualization_utils.py, have you modified the original code? Can you check again?

**Comment by beatrix-wantania** [comment]
Hello, I also got the same error, what should I do?
