### ISSUE TITLE
Not able to see video of counting people

### ISSUE THREAD

**Issue by Jitesh-Mohite** [ahmetozlu/tensorflow_object_counting_api#33]
After a lot of struggle, I am able to run this project on windows 10, but I am not able to see a visualization(video) of counting of people and bicycle inside the rectangle. 
 Could you please help us?

I am getting out like this after running python real_time_counting.py

 Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2

['person: 88%']
 person: 88
'person:': 1
mode1
writing frame
['person: 87%']

**Comment by ahmetozlu** [comment]
The output results save as an output video in default. However, if you want to see the result of each processed video frame then you should remove the comments on the **[cv2.imshow lines](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/api/object_counting_api.py#L122)** insdie of **[object_counting_api.py](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/api/object_counting_api.py)**.

**Comment by Jitesh-Mohite** [comment]
still giving the same output, Also in pycharm for cv2, it showing "no module named cv2". But  I am able to run the script. could you please help us, we are struggling for it

**Comment by Jitesh-Mohite** [comment]
Also, the count showing for **python pedestrian_counting.py** only when it crosses the red line shown in the image,
<img width="960" alt="detection" src="https://user-images.githubusercontent.com/22516970/56466829-9442e600-6434-11e9-8941-319750114720.png">
 
I want to detect the people as of earlier as possible? How I can do that?

**Comment by Jitesh-Mohite** [comment]
Also, want to show live camera feeding, I see this https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/4, but I am not sure how it will help me. Can you suggest me what are the changes I have to do?
