### ISSUE TITLE
How to access to  video duration?

### ISSUE THREAD

**Issue by erdalalim** [ahmetozlu/tensorflow_object_counting_api#35]
Hi, Iam Running  real_time_counting.py script it works great.Thanks for sharing!

I need to access to the video duration,
 I mean I need output in which second of video which objects are detected..
 ( example: 00:01 second : 1 truck,2 persons... , 00:02 second : 3 persons,1 car are detected ... etc.)

How it is possible? Or it will be upgradet on this project?

**Comment by EdwinChien** [comment]
Maybe you can try with time module or DateTime module, the first module can let you get the duration time, the second module can let you get the time which the detected by.

**Comment by erdalalim** [comment]
> Maybe you can try with time module or DateTime module, the first module can let you get the duration time, the second module can let you get the time which the detected by.

**Comment by erdalalim** [comment]
@EdwinChien Thanks for Idea, Iam new on this so if there is any example  I will try to do something according to the example. You have any suggestion?
