### ISSUE TITLE
Vehicle Counting 

### ISSUE THREAD

**Issue by amaadmirza** [ahmetozlu/tensorflow_object_counting_api#36]
Hi, can we add targeted_objects = "car, bus, truck"  in vehicle_counting.py file i want to count upon these target objects. 
how to update this code to specifically detect upon these targeted_objects = "car, bus, truck"??

need help

**Comment by ahmetozlu** [comment]
You can find it on readme: https://github.com/ahmetozlu/tensorflow_object_counting_api#2-usage-of-real-time-counting-mode 

Usage of "detecting, counting and tracking the multiple targeted objects":

    targeted_objects = "car, bus, truck" # (for counting targeted objects) change it with your targeted objects
    fps = 25 # change it with your input video fps
    width = 1280 # change it with your input video width
    height = 720 # change it with your input video height
    is_color_recognition_enabled = 0

    object_counting_api.targeted_object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled, targeted_objects, fps, width, height) # targeted objects counting
