### ISSUE TITLE
Problems in counting 

### ISSUE THREAD

**Issue by b-thebest** [ahmetozlu/tensorflow_object_counting_api#38]
If we are counting some object and when object passes through a line which counts passing of any object. But when any object stays on line, so it's keep on counting that object again and again. Please suggest a change to fix that

**Comment by ahmetozlu** [comment]
You can check the counted object center pixel coordinate in each frame to avoid counting the same object more than one. 

For example, if the counted object center coordinate does not change more than threshold value in next frame, your code will not count it so you can avoid to count same object more than one by this way!

**Comment by b-thebest** [comment]
No arguments like centroid of image are passed to function in api as well as not to function of file "object_counter.py". Pls suggest me a change in any file or function particularly, I will do it quickly then.
