### ISSUE TITLE
run with webcam live

### ISSUE THREAD

**Issue by aminatamima** [ahmetozlu/tensorflow_object_counting_api#39]
Hello,

Please how can i test it with my live webcam ?
I have tested on input videos as in showed in the tuto but i want to do live detection using my ubuntu webcam. IS there any option to do this please ?

Thank you in advance

**Comment by ahmetozlu** [comment]
added: https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/webcam_counting.py
