### ISSUE TITLE
How to count people with a live video feed

### ISSUE THREAD

**Issue by mnoggs** [ahmetozlu/tensorflow_object_counting_api#4]
Hi ahmetozlu, i want to use your api for counting the amount of people within a camera feed and then saving the number to a text file. How do i go about implementing your code into my code to do that, I have attached my code.

Please feel free to message me or alter my code in any way to get a better result. Thank you :)
![people detection](https://user-images.githubusercontent.com/42375314/44127610-78382a00-a081-11e8-8958-c07aec600a4c.png)

**Comment by ahmetozlu** [comment]
Hey,

You can use [**pedestrian_counting** ](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/pedestrian_counting.py)sample to develop your project!

BR,
Ahmet
