### ISSUE TITLE
TabError in utils/create_csv.py

### ISSUE THREAD

**Issue by cclauss** [ahmetozlu/tensorflow_object_counting_api#42]
flake8 testing of https://github.com/ahmetozlu/tensorflow_object_counting_api on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./utils/create_csv.py:38:29: E999 TabError: inconsistent use of tabs and spaces in indentation
		for subdirname in dirnames:
                            ^
1     E999 TabError: inconsistent use of tabs and spaces in indentation
1
```

**Comment by ahmetozlu** [comment]
Since this script was an unnecessary util, it was removed.
