### ISSUE TITLE
vehicle detection error

### ISSUE THREAD

**Issue by u221** [ahmetozlu/tensorflow_object_counting_api#5]
@ahmetozlu When I run vehicle_counting.py the bounding boxes are getting displayed on the vehicles but when it passes the ROI line its not getting detected. please help me with this

**Comment by mobileonekh** [comment]
Same as me. Any suggestion?

**Comment by ahmetozlu** [comment]
Please modify [**this line**](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/utils/object_counting_module/object_counter_x_axis.py#L11) as considering your case specs (for example fps)! Thus, you can improve the accuracy of object counting module.

**Comment by mobileonekh** [comment]
@ahmetozlu , i use the current code and also the sample video in this git. I don't make any change yet. but the result is 0 vehicle detected

**Comment by mbalty** [comment]
+1 to this problem

**Comment by rakash** [comment]
+1

**Comment by rakash** [comment]
same issue. any solution to this?

**Comment by ahmetozlu** [comment]
fixed

**Comment by rakash** [comment]
@ahmetozlu - what was the fix? which line / python file ?

**Comment by wiwengweng** [comment]
I think there's no so-call 'fix' here. As ahmetozlu tells, modify [the line to improve the algorithm](https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/5#issuecomment-429542274) will help.
