### ISSUE TITLE
unable to open file: name = 'mask_rcnn_barilla-spaghetti_0040.h5'

### ISSUE THREAD

**Issue by jm2004** [ahmetozlu/tensorflow_object_counting_api#52]
Hi, Thanks for sharing the code.
When I tried the sample code in: tensorflow_object_counting_api/mask_rcnn_counting_api_keras_tensorflow/barilla_spaghetti_counter_training.

I got an error"unable to open file: name = 'mask_rcnn_barilla-spaghetti_0040.h5'". I tried to look for this file, but no one was found in this repository.

How should I fix it?
Thanks

**Comment by reni1111** [comment]
Same problem over here

**Comment by borourke** [comment]
Same here, should probably be part of the requirements.txt IMO

**Comment by pagiiii** [comment]
Same problem over here.....how should i fix it???????????????

**Comment by ahmetozlu** [comment]
Please download [the file (mask_rcnn_barilla-spaghetti_0040.h5)](https://github.com/ahmetozlu/tensorflow_object_counting_api/releases/tag/mask_rcnn_barilla-spaghetti_v1.h5) and use it.
