### ISSUE TITLE
how to make a target object counter like vehicle_counting.py

### ISSUE THREAD

**Issue by myounus96** [ahmetozlu/tensorflow_object_counting_api#55]
Now the real_time_counting_targeted_object.py counting the objects and show the total detected objects in current frame,but I wanna make a target objects counter like vehicle_counting.py in which objects are counted for whole video after crossing line.
BTW your work is great,Thanks for that.

**Comment by ahmetozlu** [comment]
Please check [this sample code](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/vehicle_counting.py) again.. Targeted objects can be set as did in this [line](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/vehicle_counting.py#L23).
