### ISSUE TITLE
How add roi in real_time_counting_targeted_object.py

### ISSUE THREAD

**Issue by myounus96** [ahmetozlu/tensorflow_object_counting_api#56]
Hi there,can you please guide how to add roi in real_time_counting_targeted_object.py.
Thanks

**Comment by ahmetozlu** [comment]
[This sample code](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/vehicle_counting.py) helps you for your case. It contains roi line for real time counting.
