### ISSUE TITLE
#webcam issue

### ISSUE THREAD

**Issue by Red025** [ahmetozlu/tensorflow_object_counting_api#58]
the available webcam_counting.api is working fine with your model but when i tried running it with my training model the webcam is not running smooth. 
What can be the problem is my model? please help

**Comment by bidyutchanda** [comment]
What do you mean by 'not running smooth'? If by non-smoothness you mean the video playback is stuttering, then it is because your hardware does not support detection at a higher FPS than what you are getting currently.
