### ISSUE TITLE
Error while run single_image_object_counting.py

### ISSUE THREAD

**Issue by andhana** [ahmetozlu/tensorflow_object_counting_api#6]
When I run single_image_object_counting.py there is an error like this:

`$ python single_image_object_counting.py`
`Traceback (most recent call last):`
 ` File "single_image_object_counting.py", line 28, in <module>`
`    result = object_counting_api.single_image_object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled, fps, width, height) # targeted objects counting`
`  File "/root/tensorflow_object_counting_api/api/object_counting_api.py", line 469, in single_image_object_counting`
`    feed_dict={image_tensor: image_np_expanded})`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1058, in _run`
`    raise RuntimeError('Attempted to use a closed Session.')`
`RuntimeError: Attempted to use a closed Session.`

How to solve this?

**Comment by aari1-sowmya** [comment]
I am also getting the same error. Can any  one when help me to solve this error?

**Comment by ahmetozlu** [comment]
thanks @mobileonekh
