### ISSUE TITLE
Count for X

### ISSUE THREAD

**Issue by MentalGear** [ahmetozlu/tensorflow_object_counting_api#61]
Could this library also be used to count any non-specific object on a uniform background ?

**Comment by ahmetozlu** [comment]
Sure, it already supports counting any custom objects that are inside the label map (in other words, the frozen graph learned the custom objects while training), for example you can check [this](https://github.com/ahmetozlu/tensorflow_object_counting_api#21-for-detecting-tracking-and-counting-the-targeted-objects-with-disabled-color-prediction)!
