### ISSUE TITLE
Problem when Running with Tensorflow GPU (1.13 )

### ISSUE THREAD

**Issue by deeplogix-ashutosh** [ahmetozlu/tensorflow_object_counting_api#64]
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

**Comment by wz0424** [comment]
I have the same problem, how did you solve it?

**Comment by ahmetozlu** [comment]
It is related your TensorFlow version. Please check [this](https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/37#issuecomment-507043538).
