### ISSUE TITLE
Error while running single image object counting . py

### ISSUE THREAD

**Issue by aari1-sowmya** [ahmetozlu/tensorflow_object_counting_api#7]
I am working on a project called  " product recognition in Super Market Shelves ". I have images of shelves with products like Maggi and Dark Fantacy and I am able to detect these products with TF object detection API. Now I want to count how many number of maggi and how many number of dark fantacy is there in given image. So I thought , I can achieve this by using your TF object Counting API  and I executed Single Image Object Counting .py program. When I am executing I got error as below.
![screenshot from 2018-09-24 10-42-24](https://user-images.githubusercontent.com/39551534/45938323-8b954900-bfe6-11e8-8d05-0f1c0824fd35.png)

**Comment by aari1-sowmya** [comment]
For my project I want results as follows.
![42241094-14163cc8-7f12-11e8-83ed-68021b5e3b33](https://user-images.githubusercontent.com/39551534/45938692-ee3c1400-bfe9-11e8-8db0-403d3b590583.gif)

**Comment by aari1-sowmya** [comment]
To get these result , what type of changes that I need to do in the code. So that I can count number of maggi packets and number of Dark Fantacy packets in the given image. Please kindly help me with this.

**Comment by mobileonekh** [comment]
I also face exactly the same error as @aari1-sowmya 

Any suggestion?

**Comment by mobileonekh** [comment]
ok, i found the error. It's because of "Indentation issue" in the file object_counting_api.py.
It's not properly indent

**Comment by aari1-sowmya** [comment]
did you got results now?

**Comment by aari1-sowmya** [comment]
Where I need to remove indentations

**Comment by mobileonekh** [comment]
Replace with this file. It will work

https://www.dropbox.com/s/u3smzyg9alfmcbg/object_counting_api.py?dl=0

**Comment by ahmetozlu** [comment]
thanks @mobileonekh
