### ISSUE TITLE
Using tensorflow 2.1.0 anaconda

### ISSUE THREAD

**Issue by SaadAhmed1122** [ahmetozlu/tensorflow_object_counting_api#71]
AttributeError                            Traceback (most recent call last)
<ipython-input-6-31e4fb4cb104> in <module>
      6 is_color_recognition_enabled = 0
      7 
----> 8 object_counting_api.object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled)

~\tensorflow_object_counting_api-master\api\object_counting_api.py in object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled)
    260         width = 0
    261         with detection_graph.as_default():
--> 262           with tf.Session(graph=detection_graph) as sess:
    263             # Definite input and output Tensors for detection_graph
    264             image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')

AttributeError: module 'tensorflow' has no attribute 'Session'

**Comment by wahyu-dwil** [comment]
> AttributeError Traceback (most recent call last)
> in
> 6 is_color_recognition_enabled = 0
> 7
> ----> 8 object_counting_api.object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled)
> 
> ~\tensorflow_object_counting_api-master\api\object_counting_api.py in object_counting(input_video, detection_graph, category_index, is_color_recognition_enabled)
> 260 width = 0
> 261 with detection_graph.as_default():
> --> 262 with tf.Session(graph=detection_graph) as sess:
> 263 # Definite input and output Tensors for detection_graph
> 264 image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
> 
> AttributeError: module 'tensorflow' has no attribute 'Session'


You can use this "tf.compat.v1.Session"
 --> with with tf.compat.v1.Session(graph=detection_graph)
