### ISSUE TITLE
Running on Google Colab 

### ISSUE THREAD

**Issue by alisurajaya** [ahmetozlu/tensorflow_object_counting_api#76]
Thank you for sharing this code. I'm beginner, and I'm trying to run this code in google colab. Can someone give me instructions to doing this? Thankyou

**Comment by ahmetozlu** [comment]
If it is needed to run the codes on Google Colab, the necessary parts of the python codes must be converted to Jupyter Notebook since you just can run Jupyter Notebook on Colab.
