### ISSUE TITLE
Problem trying to load different model not in TF ZOO

### ISSUE THREAD

**Issue by sagarkar10** [ahmetozlu/tensorflow_object_counting_api#77]
I am trying to use the counting API but the backbone I want to use is EfficientDet [here](urhttps://github.com/google/automl/tree/master/efficientdet)

I tried changing the forzen_graph but it will not work due to different arch.
The tensor names are obviously not same, what is the way to proceed towards it. In fact, is it the appropriate way to approach this problem. I want the Counting API on models like EfficientDet/YOLO

Little help will be very much appreciated.

**Comment by sagarkar10** [comment]
@ahmetozlu 
please help

**Comment by ahmetozlu** [comment]
As long as **the frozen graph (.pb)** is located under [custom_frozen_inference_graph](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/custom_frozen_inference_graph) and **the label map** is located under [data](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/data), the counting API runs to detect & track & count the objects using the custom frozen graph you want to use!

**Comment by sagarkar10** [comment]
But the tensor names and tensor structures aren't same. How do I tackle that?

**Comment by aparico** [comment]
> As long as **the frozen graph (.pb)** is located under [custom_frozen_inference_graph](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/custom_frozen_inference_graph) and **the label map** is located under [data](https://github.com/ahmetozlu/tensorflow_object_counting_api/tree/master/data), the counting API runs to detect & track & count the objects using the custom frozen graph you want to use!

@sagarkar10  Did the suggestion work?
