### ISSUE TITLE
How to Run mask_RCNN_counting_api_keras Folder

### ISSUE THREAD

**Issue by Rahul214** [ahmetozlu/tensorflow_object_counting_api#86]
Hi ahmetozlu, can you tell how to run single_image_counting.py file. It's showing AttributeError: module 'tensorflow' has no attribute 'log' in google colab.
AttributeError: in user code:

    /content/tensorflow_object_counting_api/mask_rcnn_counting_api_keras_tensorflow/model.py:365 call  *
        roi_level = log2_graph(tf.sqrt(h * w) / (224.0 / tf.sqrt(image_area)))
    /content/tensorflow_object_counting_api/mask_rcnn_counting_api_keras_tensorflow/model.py:320 log2_graph  *
        return tf.log(x) / tf.log(2.0)[](url)
![issue](https://user-images.githubusercontent.com/56817517/105837213-6076f600-5ff4-11eb-848d-77035ae9dbb0.PNG)

**Comment by ahmetozlu** [comment]
Please check [this](https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/37#issuecomment-507043538).
