### ISSUE TITLE
Index out of Range Error After Reducing number of class_names

### ISSUE THREAD

**Issue by Rahul214** [ahmetozlu/tensorflow_object_counting_api#87]
Hi @ahmetozlu, we are getting list index out of range after reducing no. of class_names while running single_image_object_counting.py file in mask_rcnn_counting_api_keras_tensorflow folder. Can you please help us? Thanks!
![error](https://user-images.githubusercontent.com/56817517/106455565-5f413f80-64b2-11eb-95bb-84c4b0356497.PNG)
![class](https://user-images.githubusercontent.com/56817517/106455586-65cfb700-64b2-11eb-95a0-00190553be02.PNG)

**Comment by ahmetozlu** [comment]
Since you are using coco trained model, there have to be 80 classes in default. If you need to update classes, you have to perform transfer learning with your own data with your custom classes.
