### ISSUE TITLE
Cannot Clone, File Name Too Long

### ISSUE THREAD

**Issue by ekoziko** [ahmetozlu/tensorflow_object_counting_api#88]
fatal: cannot create directory at 'mask_rcnn_counting_api_keras_tensorflow/barilla_spaghetti_counter_training': Filename too long

![image](https://user-images.githubusercontent.com/53054342/110728361-ea68d000-81ea-11eb-961b-bd6f32bd8190.png)

**Comment by ahmetozlu** [comment]
Fixed, please try again..
