### ISSUE TITLE
Car Counting detect nothing

### ISSUE THREAD

**Issue by mobileonekh** [ahmetozlu/tensorflow_object_counting_api#9]
Hi,
I run your Vehicle Counting script, but it can't detect any vehicle. it's 0
The script run successfully but the result video can't detect any vehicle.
Anything advice?

Thanks;

**Comment by ahmetozlu** [comment]
Hi,

Could you share/show the video that you want to detect the cars on it? Thus, I can give you some recommendations.

BR,
Ahmet

**Comment by mobileonekh** [comment]
Hi @ahmetozlu , i use the video in the code itself.

https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/vehicle_survaillance.mp4

**Comment by rakash** [comment]
Hi @ahmetozlu -

Same issue. while the pedestrian script works, the car one doesnt detect. tried changing the min_threshold value as well. any thoughts?

**Comment by ahmetozlu** [comment]
fixed
