### ISSUE TITLE
requirements.txt and installation guide

### ISSUE THREAD

**Issue by makkarss929** [ahmetozlu/tensorflow_object_counting_api#93]
requirements.txt file is missing, please add that. It will be easier for us to use this package. without having version incompatibility issues. Now I am facing some issues. There should be a proper installation guide.

**Comment by makkarss929** [comment]
Which TensorFlow version is required, as TensorFlow 2.5.0 is not working

**Comment by harshita2311-coder** [comment]
hello...
tensorflow ====  2.5.0rc0

**Comment by ahmetozlu** [comment]
[requirements.txt](https://github.com/ahmetozlu/tensorflow_object_counting_api/blob/master/requirements.txt) updated, please check it again. Moreover, TensorFlow 2.x is not supported yet but it will soon.

**Comment by ahmetozlu** [comment]
[Installation Guide](https://github.com/ahmetozlu/tensorflow_object_counting_api/#installation) also updated..

**Comment by SwiftDev111** [comment]
what is the confident python version to build this project?
